[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/"
]

[start]
cmd = "npm start"
